/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * @author USER
 */

package com.abc.ui;

import com.abc.Bill;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MyJFrame extends javax.swing.JFrame {

    /*
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        openMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
                }
        ));
        jScrollPane.setViewportView(jTable);

        openMenu.setText("Open");
        openMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(openMenu);

        exitMenu.setText("Exit");
        jMenuBar.add(exitMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void openMenuMouseClicked(java.awt.event.MouseEvent evt) {
        // ---------------------------------------------
        // 在MenuBar中的Open被點擊時	
        // ---------------------------------------------     
        // 開啟FileChooser物件
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("開啟檔案");

        // 如果有選擇檔案   
        int returnVal = jFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // 設定檔案物件
            File file = jFileChooser.getSelectedFile();

            // 逐筆讀取檔案內容	
            try {
                // 產生一個BufferedReader物件, 用來逐筆讀取檔案	
                BufferedReader b = new BufferedReader(new FileReader(file));

                // 存放每次讀入的單行內容		
                String readLine = null;

                // 清除原有資料
                DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                model.setRowCount(0);

                while ((readLine = b.readLine()) != null) {
                    // 切割逗號分隔的項目
                    String items[] = readLine.split(",", -1);

                    // ================================================================
                    // (1)取出電話, 姓名, 洗鞋子數, 洗靴子數, 洗包包數, 是否快速服務
                    // ================================================================
                    String tel = items[0];
                    String name = items[1];
                    int shoes = Integer.parseInt(items[2]);
                    int boots = Integer.parseInt(items[3]);
                    int bags = Integer.parseInt(items[4]);
                    boolean fastService = Boolean.parseBoolean(items[5]);
                    String yesNo = "";
                    if (fastService) {
                        yesNo = "是";
                    } else {
                        yesNo = "否";
                    }
                    // ----------------------------------------------------------------                   

                    // ==========================================================
                    // (2)呼叫Bill類別的靜態方法fee(), 計算總費
                    // ==========================================================
                    int fee = Bill.fee(shoes, boots, bags, fastService);
                    // ----------------------------------------------------------

                    // ==================================================
                    // (3)將取出的檔位產生一個陣列, 加入表格的資料物件中
                    // ==================================================
                    Object[] row = {tel, name, shoes, boots, bags, yesNo, fee};
                    model.addRow(row);
                    // --------------------------------------------------
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "讀檔時發生錯誤!");
            }
        } else {
            System.out.println("取消檔案讀取");
        }
        // ---------------------------------------------   
    }


    // Variables declaration - do not modify                     
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    private javax.swing.JMenu openMenu;
    // End of variables declaration                   
}